### ISSUE TITLE
Fix Template-Format and Link issues

### ISSUE THREAD

**Issue by ephes** [ephes/python-podcast#24]
As described in [here](https://mastodon.social/users/neingeist/statuses/111315301997294338) - thanks @neingeist.

**Comment by neingeist** [comment]
Copy of the text (I delete old toots and it's actually a followers-only toot):

> - üblicherweise linkt die überschrift (obwohl sie nicht unterstrichen usw. ist) auch auf den artikel (= permalink)
> - das leerzeichen nach dem datum und dem komma sollte nicht mehr teil des links hinter dem datum sein  👀

**Comment by neingeist** [comment]
> > * üblicherweise linkt die überschrift (obwohl sie nicht unterstrichen usw. ist) auch auf den artikel (= permalink)

That's the header of the article in the "index.html" but I don't think it must be different on the individual article pages. I've checked some other blogs, it really is a convention at least among the ubiquitous Wordpress sites. (I also tried blogspot, where it is "broken" too it seems. But I only checked "Python Insider" and their presentation is horrible in other ways already 😃)

**Comment by ephes** [comment]
I added the date permalink because I didn't want that the headings are blue, and don't know anything about CSS. But now since there's [chatGPT I can ask, that's not a big problem anymore](https://chat.openai.com/share/4d1e1bdc-534d-4efa-8153-07852f524250).
